language : node__js
node__js :
  - 'stable'
  - 'lts/*'
install:
  - nvm install stable
  - nvm use stable
before_script :
  - npm install -g gulp-cli
  - npm install
script :
  - npm run build
  - npm run test
after_success :
  - echo build success!
after_failure :
  - echo build failure!
cache:
  directories :
  - "node_modules"